### ISSUE TITLE
Code Review for pydistinto

### ISSUE THREAD

**Issue by jdamerow** [DHCodeReview/DHCodeReview#3]
**Requester**: Keli Du (Trier Center for Digital Humanities)
**GitHub repo**: https://github.com/Zeta-and-Company/pydistinto
**Programming Language**: Python
**Authors and contributors**: The code is based on "pyzeta" which is written by Christof Schöch and further develped by Keli Du.
**Field**: contrastive text analysis

**Supporting papers**:
yes, it's based on this implementation framework: https://doi.org/10.5281/zenodo.5092328

**Standards/Required Domain Knowledge**:

**Requirements**:

**Anything else**:

**Comment by jdamerow** [comment]
@dkltimon are there any specific parts of the program that the reviewers should focus on? It looks like there is quite a bit of code, so we are wondering how much can be achieved in about an hour? Are there any parts that you especially like feedback on?

**Comment by dkltimon** [comment]
@jdamerow It would be very helpful, if the code in the [calculate_simple.py](https://github.com/DHCodeReview/pydistinto/tree/main/scripts/pipeline/calculate_simple.py)-script could be reviewed and we could get some suggestions for improvement. Thank you very much!

**Comment by jdamerow** [comment]
I've created a pull request for the review here: https://github.com/DHCodeReview/pydistinto/pull/1.

**Comment by maehr** [comment]
Thank you @dkltimon for submitting code. I finished my review. I couldn't look into the functionality in one hour too much but there's a lot of potential for simplification and documentation. I hope you find it helpful. I tried to keep it short and instructive.
