### ISSUE TITLE
Code Review for Citationnet

### ISSUE THREAD

**Issue by maltevogl** [DHCodeReview/DHCodeReview#8]
Requester: Malte Vogl
GitHub repo: https://github.com/maltevogl/citationnet
Programming Language: Javascript and Python
Authors and contributors: Malte Vogl and Robert Egel - primary code authors
Field: history of science / digital humanities

Supporting papers: n/a

Standards/Required Domain Knowledge: uses flask framework to run the interface, main visualization is a 3D network in Javascript. 

Requirements:

Anything else:
I am pretty solid in Python but have no knowledge in Javascript best-practices. I would need feedback on the js files mostly. Any additional feedback is most welcome.  For running the code, the readme should give enough information.

**Comment by jdamerow** [comment]
Reviewers: Rebecca Sutton Koeser, Raff Viglianti

**Comment by maltevogl** [comment]
As an addition: There is a running version showing the 3D graphs accessible here: 

https://modelsen.gea.mpg.de/citationnet/

You can use Choose file to select the Bastidas.. example.
